spring.application.name=cooperari

spring.datasource.url=jdbc:postgresql://localhost:5432/cooperariDB
spring.datasource.username=cooperari
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect